version: 2
jobs:
  build-publish-trigger:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Build image, test it, tag, publish it
          command: true

workflows:
  version: 2
  build-publish-trigger:
    jobs:
      - build-publish-trigger:
          context: cyberdojo-context
          filters:
            branches:
              only:
                  - master
