
version: 2.1
jobs:
  build:
    machine:
      image: 'ubuntu-1604:201903-01'
    environment:
      HELM_VERSION: v2.16.0

    steps:
        - checkout

        - run:
            name: Setup k3s and helm
            command: |
              cd build_scripts
              sudo ./install_k3s_helm.sh ${HELM_VERSION}
              echo "Installed k3s and helm"

        - run:
            name: Deploy cyber-dojo
            command: |
              cd build_scripts
              sudo ./deploy_cyber_dojo.sh
              echo "Deployed cyber-dojo"
