version: 2.1
jobs:
  build:
    machine:
      image: 'ubuntu-1604:201903-01'
    steps:
        - checkout
        - run:
            name: Init
            command: |
              ls -al
              echo "Code is here"
              cd .circleci
              sudo ./utils.sh
              echo "Install dependancies complete"
              sudo ./deploy.sh
              echo "Deploying cyberdojo complete"


