version: 2.1
jobs:
  build:
    machine:
      image: 'circleci/classic:latest'
    steps:
        - checkout
        - run:
            name: Init
            command: |
              ls -al
              echo "Code is here"
              cd .circleci
              ./utils.sh
              echo "Install dependancies complete"
              ./deploy.sh
              echo "Deploying cyberdojo complete"


