version: 2.1
jobs:
  build:
    machine:
      image: 'ubuntu-1604:201903-01'
    environment:
      HELM_VERSION: v2.14.1

    working_directory: ~/.circleci
    steps:
        - checkout
        
        - run:
            name: Setup k3s and helm
            command: |
              sudo ./utils.sh ${HELM_VERSION}
              echo "Install dependancies complete"

        - run:
            name: Deploy cyberdojo
            command: |
              sudo ./deploy.sh
              echo "Deploying cyberdojo complete"


