#!/bin/bash -Eeu

# initialize
readonly INSTALLER_DIR=installer
readonly INSTALLER_ENV=${INSTALLER_DIR}/env
readonly INSTALLER_USER_VALUES_DIR=${INSTALLER_DIR}
readonly INSTALLER_SH_DIR=${INSTALLER_DIR}/sh
readonly INSTALLER_DEFAULT_VALUES_DIR=${INSTALLER_DIR}/default-values

mkdir  -p ${INSTALLER_DIR}
rm -rf ${INSTALLER_DIR}/*
mkdir  -p ${INSTALLER_SH_DIR}
mkdir  -p ${INSTALLER_DEFAULT_VALUES_DIR}
mkdir  -p ${INSTALLER_USER_VALUES_DIR}

readonly GITHUB_RAW_CONTENT=https://raw.githubusercontent.com
readonly GITHUB_ORGANIZATION=cyber-dojo
readonly REPO_VALUES_YML=k8s-general-values.yml

curl ${GITHUB_RAW_CONTENT}/${GITHUB_ORGANIZATION}/versioner/master/app/.env > ${INSTALLER_ENV}

curl ${GITHUB_RAW_CONTENT}/${GITHUB_ORGANIZATION}/k8s-install/master/sh/deployment_functions.sh > ${INSTALLER_SH_DIR}/deployment_functions.sh
cp install.sh.resource ${INSTALLER_DIR}/install.sh
chmod a+x ${INSTALLER_DIR}/install.sh

source ${INSTALLER_ENV}

# CUSTOM_START_POINTS
REPO=custom-start-points
SHA="${CYBER_DOJO_CUSTOM_START_POINTS_SHA}"

curl ${GITHUB_RAW_CONTENT}/${GITHUB_ORGANIZATION}/${REPO}/${SHA}/.circleci/${REPO_VALUES_YML} \
  > ${INSTALLER_DEFAULT_VALUES_DIR}/${REPO}-${REPO_VALUES_YML}

# LANGUAGES_START_POINTS
REPO=languages-start-points
SHA="${CYBER_DOJO_LANGUAGES_START_POINTS_SHA}"

curl ${GITHUB_RAW_CONTENT}/${GITHUB_ORGANIZATION}/${REPO}/${SHA}/.circleci/${REPO_VALUES_YML} \
  > ${INSTALLER_DEFAULT_VALUES_DIR}/${REPO}-${REPO_VALUES_YML}

# EXERCISES_START_POINTS
REPO=exercises-start-points
SHA="${CYBER_DOJO_EXERCISES_START_POINTS_SHA}"

curl ${GITHUB_RAW_CONTENT}/${GITHUB_ORGANIZATION}/${REPO}/${SHA}/.circleci/${REPO_VALUES_YML} \
  > ${INSTALLER_DEFAULT_VALUES_DIR}/${REPO}-${REPO_VALUES_YML}

# CREATOR
REPO=creator
SHA="${CYBER_DOJO_CREATOR_SHA}"

curl ${GITHUB_RAW_CONTENT}/${GITHUB_ORGANIZATION}/${REPO}/${SHA}/.circleci/${REPO_VALUES_YML} \
  > ${INSTALLER_DEFAULT_VALUES_DIR}/${REPO}-${REPO_VALUES_YML}

# CUSTOM_CHOOSER
REPO=custom-chooser
SHA="${CYBER_DOJO_CUSTOM_CHOOSER_SHA}"

curl ${GITHUB_RAW_CONTENT}/${GITHUB_ORGANIZATION}/${REPO}/${SHA}/.circleci/${REPO_VALUES_YML} \
  > ${INSTALLER_DEFAULT_VALUES_DIR}/${REPO}-${REPO_VALUES_YML}


# EXERCISES_CHOOSER
REPO=exercises-chooser
SHA="${CYBER_DOJO_EXERCISES_CHOOSER_SHA}"

curl ${GITHUB_RAW_CONTENT}/${GITHUB_ORGANIZATION}/${REPO}/${SHA}/.circleci/${REPO_VALUES_YML} \
  > ${INSTALLER_DEFAULT_VALUES_DIR}/${REPO}-${REPO_VALUES_YML}


# LANGUAGES_CHOOSER
REPO=languages-chooser
SHA="${CYBER_DOJO_LANGUAGES_CHOOSER_SHA}"

curl ${GITHUB_RAW_CONTENT}/${GITHUB_ORGANIZATION}/${REPO}/${SHA}/.circleci/${REPO_VALUES_YML} \
  > ${INSTALLER_DEFAULT_VALUES_DIR}/${REPO}-${REPO_VALUES_YML}

# AVATARS
REPO=avatars
SHA="${CYBER_DOJO_AVATARS_SHA}"

curl ${GITHUB_RAW_CONTENT}/${GITHUB_ORGANIZATION}/${REPO}/${SHA}/.circleci/${REPO_VALUES_YML} \
  > ${INSTALLER_DEFAULT_VALUES_DIR}/${REPO}-${REPO_VALUES_YML}

# DIFFER
REPO=differ
SHA="${CYBER_DOJO_DIFFER_SHA}"

curl ${GITHUB_RAW_CONTENT}/${GITHUB_ORGANIZATION}/${REPO}/${SHA}/.circleci/${REPO_VALUES_YML} \
  > ${INSTALLER_DEFAULT_VALUES_DIR}/${REPO}-${REPO_VALUES_YML}

# RUNNER
REPO=runner
SHA="${CYBER_DOJO_RUNNER_SHA}"

curl ${GITHUB_RAW_CONTENT}/${GITHUB_ORGANIZATION}/${REPO}/${SHA}/.circleci/${REPO_VALUES_YML} \
  > ${INSTALLER_DEFAULT_VALUES_DIR}/${REPO}-${REPO_VALUES_YML}

# SAVER
REPO=saver
SHA="${CYBER_DOJO_SAVER_SHA}"

curl ${GITHUB_RAW_CONTENT}/${GITHUB_ORGANIZATION}/${REPO}/${SHA}/.circleci/${REPO_VALUES_YML} \
  > ${INSTALLER_DEFAULT_VALUES_DIR}/${REPO}-${REPO_VALUES_YML}
  
cp saver-pvc.yml ${INSTALLER_USER_VALUES_DIR}/saver-pvc.yml

# REPLER
REPO=repler
SHA="${CYBER_DOJO_REPLER_SHA}"

curl ${GITHUB_RAW_CONTENT}/${GITHUB_ORGANIZATION}/${REPO}/${SHA}/.circleci/${REPO_VALUES_YML} \
  > ${INSTALLER_DEFAULT_VALUES_DIR}/${REPO}-${REPO_VALUES_YML}

# SHAS

REPO=shas
SHA="${CYBER_DOJO_SHAS_SHA}"

curl ${GITHUB_RAW_CONTENT}/${GITHUB_ORGANIZATION}/${REPO}/${SHA}/.circleci/${REPO_VALUES_YML} \
  > ${INSTALLER_DEFAULT_VALUES_DIR}/${REPO}-${REPO_VALUES_YML}

# WEB
REPO=web
SHA="${CYBER_DOJO_WEB_SHA}"

curl ${GITHUB_RAW_CONTENT}/${GITHUB_ORGANIZATION}/${REPO}/${SHA}/.circleci/${REPO_VALUES_YML} \
 > ${INSTALLER_DEFAULT_VALUES_DIR}/${REPO}-${REPO_VALUES_YML}

# NGINX
REPO=nginx
SHA="${CYBER_DOJO_NGINX_SHA}"

curl ${GITHUB_RAW_CONTENT}/${GITHUB_ORGANIZATION}/${REPO}/${SHA}/.circleci/${REPO_VALUES_YML} \
  > ${INSTALLER_DEFAULT_VALUES_DIR}/${REPO}-${REPO_VALUES_YML}

cp nginx-ingress.yml ${INSTALLER_USER_VALUES_DIR}/nginx-ingress.yml
